services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
    networks:
      - rabbit_net

  gateway-migrate:
    build: .
    command: alembic upgrade head   # sovrascrive il comando di avvio eseguendo solo le migrazioni
    depends_on:
      - gateway_db
    networks:
      - gateway_net
    deploy:
      replicas: 1   # forza una sola istanza
    restart: "no"   # non viene riavviato

  gateway:
    build: .
    command: gunicorn -k uvicorn.workers.UvicornWorker app.main:app --bind 0.0.0.0:8000 --workers 1
    ports:
      - "8000:8000"
    depends_on:
      - gateway_db
      - gateway-migrate
    networks:
      - gateway_net
      - rabbit_net
    restart: unless-stopped

  gateway_db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: gateway
    volumes:
      - gateway_db_data:/var/lib/postgresql/data
    networks:
      - gateway_net
    restart: unless-stopped

volumes:
  gateway_db_data:

networks:
  gateway_net:
  rabbit_net:
    driver: bridge