"""aggiunto campo sessione bloccata

Revision ID: 748c51f69ad4
Revises: 8de4697c08fd
Create Date: 2025-08-20 18:21:13.744660

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '748c51f69ad4'
down_revision: Union[str, Sequence[str], None] = '8de4697c08fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('is_blocked', sa.Boolean(), nullable=False,
                                        server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'is_blocked')
    # ### end Alembic commands ###
