"""aggiunte sessioni

Revision ID: 9bb181108a07
Revises: ebb59c01d892
Create Date: 2025-08-20 11:44:01.081747

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9bb181108a07'
down_revision: Union[str, Sequence[str], None] = 'ebb59c01d892'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('expires_at', sa.DateTime(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'),
                              nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'),
                              nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('tokens') as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('is_expired', sa.Boolean(), nullable=False))
        batch_op.drop_index(op.f('ix_tokens_access_token'))
        batch_op.drop_index(op.f('ix_tokens_refresh_token'))
        batch_op.drop_constraint(op.f('fk_tokens_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_tokens_session_id_sessions', 'sessions', ['session_id'], ['id'])
        batch_op.drop_column('refresh_token')
        batch_op.drop_column('user_id')
        batch_op.drop_column('access_token')
        batch_op.drop_column('is_active')
        batch_op.drop_column('expires_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('expires_at', sa.DATETIME(), nullable=False))
    op.add_column('tokens', sa.Column('is_active', sa.BOOLEAN(), nullable=False))
    op.add_column('tokens', sa.Column('access_token', sa.VARCHAR(), nullable=False))
    op.add_column('tokens', sa.Column('user_id', sa.INTEGER(), nullable=False))
    op.add_column('tokens', sa.Column('refresh_token', sa.VARCHAR(), nullable=False))
    op.drop_constraint(None, 'tokens', type_='foreignkey')
    op.create_foreign_key(op.f('fk_tokens_user_id_users'), 'tokens', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_tokens_refresh_token'), 'tokens', ['refresh_token'], unique=1)
    op.create_index(op.f('ix_tokens_access_token'), 'tokens', ['access_token'], unique=1)
    op.drop_column('tokens', 'is_expired')
    op.drop_column('tokens', 'session_id')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###
