"""aggiunto token in token

Revision ID: e22e169aaf3b
Revises: 9bb181108a07
Create Date: 2025-08-20 11:52:19.195379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e22e169aaf3b'
down_revision: Union[str, Sequence[str], None] = '9bb181108a07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokens') as batch_op:
        batch_op.add_column(sa.Column('token', sa.String(), nullable=False))
        batch_op.create_unique_constraint('uq_tokens_token', ['token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokens') as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('token')
    # ### end Alembic commands ###
