"""modificato campo password utente

Revision ID: ff693a6cb917
Revises: 3344bc248076
Create Date: 2025-08-20 11:02:05.135490

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ff693a6cb917'
down_revision: Union[str, Sequence[str], None] = '3344bc248076'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    op.drop_index(op.f('ix_users_password'), table_name='users')
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=80), nullable=False))
    op.create_index(op.f('ix_users_password'), 'users', ['password'], unique=False)
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
